"""Public acquisition pages and forms. Generated by build.py, never at request time."""
from build import *

# (value sent to us, label shown on the chip). A twelve-option dropdown on a
# phone is a picker to open, a list to scroll and a sheet to dismiss; the same
# choices as chips are one tap, and visible, so people can see what is on offer
# instead of discovering it inside a menu. Short labels keep the block compact
# while the full wording still reaches the enquiry email.
SERVICE_CHOICES = [
    ("Website design & development", "Website"),
    ("Mobile app development", "Mobile app"),
    ("UI/UX & product design", "UI/UX"),
    ("Custom software & SaaS", "Software"),
    ("CRM / ERP / HRMS / LMS / billing", "CRM & ERP"),
    ("Digital marketing & SEO", "SEO"),
    ("AI & business automation", "Automation"),
    ("Branding, IT & cloud support", "Branding & IT"),
    ("Website review / audit", "Site review"),
    ("Maintenance & support", "Maintenance"),
    ("Something else", "Other"),
]
SERVICE_OPTIONS = [value for value, _ in SERVICE_CHOICES]

# "websites" deliberately carries no city. It was titled "... | MUCO LABS,
# Erode" and shared 30% of its title, description and h1 vocabulary with
# /website-development-erode -- two pages arguing for the same query, which
# splits the signal rather than doubling it. The service page now owns the
# service intent and the Erode page owns the local one.
#
# The rest gained a real modifier rather than a keyword: several sat at 43-49
# rendered characters, which leaves usable width unused in a result listing.
SERVICE_SEARCH_TITLES = {
    "websites": "Website Design & Development Services | MUCO LABS",
    "mobile": "Mobile App Development in Erode | Android & iOS | MUCO LABS",
    "product-design": "UI/UX & Product Design in Erode | Web & Mobile | MUCO LABS",
    "software": "Custom Software & SaaS Development in Erode | MUCO LABS",
    "business-systems": "CRM, ERP, HRMS & Billing Software in Erode | MUCO LABS",
    "marketing": "SEO & Digital Marketing Services in Erode | MUCO LABS",
    "ai-automation": "AI & Business Automation Services in Erode | MUCO LABS",
    "support": "Branding, IT & Cloud Support Services in Erode | MUCO LABS",
}


def service_resources(slug):
    links = {
        "websites": [("business-website-growth", "Website and local search launch scope"), ("website-cost-erode", "What affects website cost?"), ("website-development-erode", "Website development in Erode")],
        "marketing": [("website-audit", "Review your existing website"), ("business-website-growth", "Plan a local search foundation")],
        "software": [("textile-software", "Textile order and job-work workflows"), ("pricing", "How a custom software quote is scoped")],
        "business-systems": [("textile-software", "Connecting orders, stock and job work")],
        "ai-automation": [("textile-software", "Start with a defined business workflow"), ("work#lead-automation", "Internal lead-automation example")],
    }.get(slug, [("work", "Browse our builds and technical examples"), ("pricing", "Understand scope and ongoing costs")])
    return '<section class="section-divider"><div class="container"><h2>Useful next reads</h2><ul class="feature-list">%s</ul></div></section>' % "".join('<li><a href="%s">%s</a></li>' % pair for pair in links)


def field(name, label, kind="text", required=False, limit=120, autocomplete="", hint="", placeholder=""):
    return '''<div class="form-group"><label for="lead-{name}">{label}{star}</label>
      <input class="form-control" id="lead-{name}" name="{name}" type="{kind}" maxlength="{limit}"
        {required} {autocomplete} placeholder="{placeholder}" aria-describedby="hint-{name} err-{name}">
      <p class="form-hint" id="hint-{name}">{hint}</p><p class="form-error" id="err-{name}"></p></div>'''.format(
        name=name, label=label, star=' <span class="form-req">*</span>' if required else "",
        kind=kind, limit=limit, required="required" if required else "",
        autocomplete='autocomplete="%s"' % autocomplete if autocomplete else "",
        hint=hint, placeholder=escape(placeholder, quote=True))


def public_lead_form(audit=False, preselect=""):
    name = field("name", "Your name", required=True, limit=100, autocomplete="name", placeholder="Your full name")
    phone = field("phone", "Phone / WhatsApp", "tel", True, 32, "tel", "Include your country code if outside India.", "+91 …")
    business = field("business", "Business name (optional)", autocomplete="organization", hint="Leave it blank if you are still deciding.")
    email = field("email", "Email (optional)", "email", limit=160, autocomplete="email", placeholder="you@example.com")
    website = field("website", "Website URL" if audit else "Existing website (optional)", "url", audit, 300,
                    hint="Use the full address, starting with https://.", placeholder="https://example.com")
    assert not preselect or preselect in SERVICE_OPTIONS, (
        "preselect %r is not one of the service choices" % preselect)
    service = '''<fieldset class="form-group service-picker" aria-describedby="err-service">
      <legend>What do you need? <span class="form-req">*</span></legend>
      <div class="service-chips">%s</div>
      <p class="form-error" id="err-service"></p></fieldset>''' % "".join(
        '<label class="service-chip"><input type="radio" name="service" value="%s"%s'
        ' aria-describedby="err-service"%s><span>%s</span></label>'
        % (escape(value, quote=True), " checked" if value == preselect else "",
           " required" if index == 0 else "", escape(label))
        for index, (value, label) in enumerate(SERVICE_CHOICES))
    # The project requirement is the one answer that makes an enquiry worth
    # anything, so it is visible and required. It used to sit inside the
    # collapsed "optional details" disclosure, which meant most people never
    # saw it and the studio received enquiries with no brief attached.
    requirement = '''<div class="form-group"><label for="lead-message">What do you want built or fixed? <span class="form-req">*</span></label>
      <textarea class="form-control" id="lead-message" name="message" maxlength="4000" rows="4" required
        placeholder="What is happening today, and what would you like to improve?"
        aria-describedby="hint-message err-message"></textarea>
      <p class="form-hint" id="hint-message">A sentence or two is enough. It is the fastest way to a useful reply.</p>
      <p class="form-error" id="err-message"></p></div>'''
    optional = email if audit else '''<details class="lead-optional"><summary>Add business name, budget, timeline and links (optional)</summary>
      <div class="form-row">%s%s</div><div class="form-row">%s%s</div><div class="form-row">%s</div></details>''' % (
        business, email, website, field("budget", "Budget (optional)", limit=60, placeholder="A range or not decided"),
        field("timeline", "Timeline (optional)", limit=60, placeholder="When would you like to start?"))
    # method and action are declared so a browser with no working JavaScript posts
    # the enquiry in the request body. Without them the HTML default is a GET to
    # this same page, which puts the customer's name, phone, email and message
    # into the URL -- and so into browser history, access logs and the Referrer
    # header of the next navigation -- while losing the enquiry entirely. main.js
    # calls preventDefault and sends JSON; api/lead.js answers a form-encoded post
    # with an HTML confirmation instead. The fieldset is no longer shipped
    # disabled: the form now works without scripting, so disabling it would take
    # away a path that functions.
    return '''<form class="form-card public-lead-form" id="lead-form" data-form-type="{kind}" data-clarity-mask="true"
      method="post" action="/api/lead" novalidate>
      <span id="start-project" class="anchor-target" aria-hidden="true"></span>
      <h2>{heading}</h2><p class="form-intro">{intro} Fields marked * are required.</p>
      <fieldset class="lead-fields"><legend class="visually-hidden">Your enquiry</legend>
      {website}{service}<div class="form-row">{name}{phone}</div>
      {requirement}{optional}
      <div class="lead-honeypot" aria-hidden="true"><label for="lead-company-website">Leave this field empty</label>
        <input id="lead-company-website" name="company_website" type="text" tabindex="-1" autocomplete="off"></div>
      <div class="form-group"><label class="consent-label" for="lead-consent">
        <input id="lead-consent" name="consent" type="checkbox" required aria-describedby="err-consent">
        <span>I agree that MUCO LABS may contact me about this enquiry. <a href="privacy.html">Privacy policy</a>.</span></label>
        <p class="form-error" id="err-consent"></p></div>
      <input type="hidden" name="form_type" value="{kind}">
      <button class="btn btn-accent btn-lg" type="submit" id="lead-submit">{submit}</button></fieldset>
      <noscript><p>This form works without JavaScript &mdash; your details are sent securely and
        confirmed on the next page. You can also reach us directly using the links below.</p></noscript>
      <p class="form-status" id="lead-status" role="status" aria-live="polite" tabindex="-1"></p>
      <p class="form-hint">{process}</p>
      <div class="btn-group lead-fallback"><a class="btn btn-whatsapp" href="{wa}" data-whatsapp>WhatsApp MUCO LABS</a>
        <a class="btn btn-secondary" href="tel:+916381809844">Call</a><a class="text-link" href="mailto:{email_address}">Email us</a></div>
    </form>'''.format(kind="audit" if audit else "project", name=name, phone=phone,
        requirement="" if audit else requirement,
        website=website if audit else "", service='<input type="hidden" name="service" value="Website review / audit">' if audit else service,
        optional=optional, heading="Request a Website Review" if audit else "Start a Project",
        intro="Send the website you would like us to review. No account needed." if audit else "Tell us the essentials. No account needed.",
        submit="Request my free review" if audit else "Send my enquiry",
        process="We will confirm a review time, then send prioritised findings. Submitting this form does not run an automated audit." if audit else "We review your requirement, ask any follow-up questions and agree the next step with you.",
        wa=WHATSAPP_URL, email_address=EMAIL)



def contact_section(eyebrow, heading, lead, preselect="", level=2):
    """The contact block: ways to reach a person on the left, the form on the right.

    One implementation for /contact and for the foot of every service page. A
    service page ending in a centred box with two buttons asked a reader who had
    just spent two thousand words deciding to go and find the form somewhere
    else; this puts it in front of them with their service already chosen.
    """
    tag = "h%d" % level
    # No id here: public_lead_form already carries the #start-project anchor,
    # and two elements sharing it is invalid HTML -- getElementById would find
    # whichever came first, which is not the form.
    return '''    <section class="contact-hero">
      <div class="contact-hero-glow" aria-hidden="true"></div>
      <div class="container">
        <div class="contact-grid">

          <div class="contact-intro">
            <span class="eyebrow">%(eyebrow)s</span>
            <%(tag)s>%(heading)s</%(tag)s>
            <p class="lead">%(lead)s</p>

            <div class="contact-lines">
              <a class="contact-line" href="%(wa)s" data-whatsapp>
                <span class="contact-line-icon" aria-hidden="true">%(wa_icon)s</span>
                <span class="contact-line-text">
                  <b>WhatsApp</b>
                  <small>Usually the fastest. Tamil or English.</small>
                </span>
                <span class="contact-line-go" aria-hidden="true">&rarr;</span>
              </a>
              <a class="contact-line" href="%(call)s">
                <span class="contact-line-icon" aria-hidden="true">%(call_icon)s</span>
                <span class="contact-line-text">
                  <b>%(phone)s</b>
                  <small>%(hours)s</small>
                </span>
                <span class="contact-line-go" aria-hidden="true">&rarr;</span>
              </a>
              <a class="contact-line" href="mailto:%(email)s">
                <span class="contact-line-icon" aria-hidden="true">%(mail_icon)s</span>
                <span class="contact-line-text">
                  <b>%(email)s</b>
                  <small>Best for anything with attachments.</small>
                </span>
                <span class="contact-line-go" aria-hidden="true">&rarr;</span>
              </a>
            </div>

            <dl class="contact-facts">
              <div><dt>Where we are</dt><dd>%(city)s, %(region)s &mdash; in person across the
                district, remote everywhere else.</dd></div>
              <div><dt>What it costs to ask</dt><dd>Nothing. A written scope is free and
                carries no obligation.</dd></div>
            </dl>

            <p class="contact-social">%(social)s</p>
          </div>

          <div class="contact-panel">
            %(form)s
          </div>

        </div>
      </div>
    </section>
''' % {
        "eyebrow": eyebrow,
        "tag": tag,
        "heading": heading,
        "lead": lead,
        "wa": WHATSAPP_URL,
        "call": CALL_URL,
        "phone": PHONE,
        "hours": HOURS,
        "email": EMAIL,
        "city": CITY,
        "region": REGION,
        "social": "".join(
            '<a class="contact-social-link" href="%s" rel="me noopener">%s</a>' % (url, name)
            for name, url in SOCIAL_LINKS),
        "form": public_lead_form(preselect=preselect),
        # WA_SVG is the filled brand mark, not a stroke path set, so it does not
        # go through icon().
        "wa_icon": WA_SVG,
        "call_icon": icon(ICONS["phone"], 18),
        "mail_icon": icon(ICONS["mail"], 18),
    }


def build_public_contact():
    """The contact page is now the shared section plus the follow-up note.

    It used to hold its own copy of that markup. The service pages needed the
    same block, and two copies of a contact section is how the phone number
    ends up formatted one way here and another way there.
    """
    body = contact_section(
        "Talk to the founder",
        "Tell us what you want built, and we will tell you what it "
        "<span class=\"accent-serif\">actually takes</span>.",
        "No account, no sign-in, no sales sequence. Whichever way you get in touch, "
        "the reply comes from %s &mdash; the person who would do the work." % FOUNDER,
        level=1,
    ) + '''    <section class="section-divider">
      <div class="container container-narrow">
        <div class="section-head">
          <span class="eyebrow">After you send it</span>
          <h2>What happens to your enquiry</h2>
        </div>
        <ol class="feature-list">
          <li>We read your requirement and clarify the business problem behind it.</li>
          <li>We agree a discovery conversation if it is useful, then prepare a written
            scope and quote.</li>
          <li>You decide whether to proceed. Nothing is charged for reaching that point.</li>
        </ol>
        <p>Want an existing website checked first?
          <a href="website-audit.html">Request a free website review</a>.</p>
      </div>
    </section>
'''

    return render("contact.html", "Start a Project with MUCO LABS | Erode, India & Remote",
        "Talk to MUCO LABS in Erode about your website, app or software. WhatsApp, phone, "
        "email or the enquiry form. A written scope costs nothing and no account is needed.",
        body,
        schema_blocks=[ORG_JSONLD, json.dumps({
            "@context": "https://schema.org", "@type": "ContactPage",
            "url": DOMAIN + "/contact",
            "about": {"@id": DOMAIN + "/#organization"}}),
            breadcrumbs([("Home", ""), ("Contact", "contact")])])


def home_growth_sections():
    problems = [
        ("I need a website customers can find", "Business website, local search setup and clear enquiry actions.", "business-website-growth"),
        ("My website gets no enquiries", "Review mobile usability, search visibility and the path to contact.", "website-audit"),
        ("My business is hard to find on Google", "Check local relevance, your Business Profile and service pages.", "services-marketing"),
        ("Orders and customer details are in spreadsheets", "Connect enquiries, follow-ups, orders and reporting.", "services-business-systems"),
        ("My team repeats the same office tasks", "Plan automation with review steps and exception handling.", "services-ai-automation"),
        ("Our textile orders are difficult to track", "Map samples, job work, stock movements and dispatch.", "textile-software"),
    ]
    cards = "".join('<a class="card card-interactive" href="%s"><h3>%s</h3><p>%s</p><span class="card-cta">Explore the next step &rarr;</span></a>' % (u, t, d) for t, d, u in problems)
    return '''<section class="section-divider"><div class="container"><div class="split">
      <div><span class="eyebrow">A practical place to start</span><h2>A business website with a clear route to an enquiry.</h2>
      <p class="lead">For local businesses that need a professional online presence and a simple way for customers to get in touch.</p>
      <a class="btn btn-accent" href="business-website-growth">Explore the website & local search offer</a></div>
      <div class="card card-lg"><h3>Agree one clear launch scope</h3><ul class="feature-list">
      <li>Business website with clear service pages</li><li>Local search foundation and Google Business Profile support</li>
      <li>WhatsApp, phone and public enquiry form</li><li>Analytics to measure enquiry actions</li>
      <li>Code ownership and a written handover</li></ul><p class="note mt-5">Custom quote. Domain, hosting, ongoing SEO and advertising are itemised separately.</p></div>
      </div></div></section><section class="section-divider"><div class="container">
      <div class="section-head"><span class="eyebrow">Start with the problem</span><h2>What can we help you fix?</h2></div>
      <div class="grid grid-3">%s</div></div></section>''' % cards


GROWTH_PAGES = {
    "business-website-growth": {
        "title": "Business Website & Local Search Setup | MUCO LABS, Erode",
        "description": "Launch a business website with local search setup, Google Business Profile support, WhatsApp enquiries and analytics. Founder-led delivery from Erode.",
        "h1": "A business website built around customer enquiries.",
        "label": "Website & local search setup", "service": "Website design & development",
        "lead": "MUCO LABS helps businesses in Erode and Tamil Nadu put their services online, make contact simple and measure which pages lead to enquiries. We agree the deliverables in a written scope before the build begins.",
        "sections": [
            ("Scope", "What the launch scope can include", '<ol class="feature-list"><li><strong>A clear business website:</strong> services, location, real product or work evidence and contact details, designed for phones as well as desktops.</li><li><strong>A local search foundation:</strong> useful service copy, titles, canonical URLs, sitemap and indexability checks.</li><li><strong>Google Business Profile support:</strong> review the genuine business name, category, service areas and contact details. Profile access, eligibility and verification remain with the business owner and Google.</li><li><strong>An enquiry system:</strong> direct WhatsApp and call links plus a public form with confirmed receipt.</li><li><strong>Measurement and handover:</strong> agreed analytics events, account ownership, source code and editing guidance.</li></ol>'),
            ("Fit", "Who this suits", '<p>A local service business, shop or professional practice whose customers need to understand the offer before contacting it. If customers need product stock, checkout, delivery or recurring bookings, we scope those workflows separately. A social profile can support discovery; the website provides a stable place for your complete service information.</p>'),
            ("What we need", "What we need from you", '<p>Your business name, actual service area, contact details, service list, logo and real photos or work examples. We review what is ready and identify content gaps before promising a launch date. You approve the copy and scope before publication.</p>'),
            ("Costs", "One-time build and ongoing costs", '<p>The quote separates design, development and launch from domain renewal, hosting, email, software subscriptions, maintenance and ongoing SEO. Advertising spend and payment gateway fees are separate. No standard price is published until the scope and commercial terms are agreed.</p><p>Read the <a href="website-cost-erode">website cost guide</a> and <a href="pricing">how we quote</a>.</p>'),
            ("Proof", "How we check the result", '<p>Before handover we test service links, forms, mobile layouts and crawlable page content. After launch, use actual enquiry records and Search Console data to decide what to improve. Search indexing, ranking and enquiry volume cannot be guaranteed by a website build.</p><p>Explore <a href="services-websites">website development</a>, <a href="services-marketing">SEO and digital marketing</a>, or <a href="website-development-erode">working with us in Erode</a>.</p>'),
        ],
        "faqs": [("Is monthly SEO included in the website build?", "A launch search foundation can be included in the written scope. Ongoing content, profile updates, monitoring and SEO improvements are a separate recurring service."),
                 ("Can I speak to you without creating an account?", "Yes. Use the public enquiry form, WhatsApp, phone or email. The customer workspace is for agreed project work."),
                 ("Can you work with a business outside Erode?", "Yes. We can scope remote delivery using calls, shared documents and review milestones. Local-profile work must reflect your actual business location and eligibility.")],
    },
    "textile-software": {
        "title": "Textile Order & Job Work Software in Erode | MUCO LABS",
        "description": "Plan custom textile software for orders, sample approvals, job work, stock, costing and dispatch. Founder-led workflow discovery with MUCO LABS in Erode.",
        "h1": "Keep textile orders, job work and stock connected.", "label": "Textile workflow software", "service": "CRM / ERP / HRMS / LMS / billing",
        "lead": "For a textile or garment business, the first useful system is often a shared order record that follows the work from buyer requirements to dispatch. MUCO LABS in Erode can scope a custom workflow around your existing process. The examples below illustrate a proposed solution; they are not claimed client results.",
        "sections": [
            ("The order record", "Start with the order and its approved specification", '<p>Record the buyer, order reference, fabric or garment specification, colour, size mix, quantity, agreed date and attachments. Keep sample versions and approval notes against that record, so a later change does not silently replace the instruction production used.</p>'),
            ("Job work", "Track job work as a movement of work and material", '<p>For each job-work issue, capture the processor, material or batch, quantity sent, expected return and operation. On receipt, reconcile returned quantity, accepted quantity, rejects and outstanding balance. Owners can see what is outside the business without searching several WhatsApp conversations.</p>'),
            ("Stock and costing", "Separate stock, costing and dispatch", '<p>A stock movement needs a unit, location and reason; mixing metres, kilograms and pieces in one unlabelled total creates confusion. Costing can track material, processing, labour and agreed wastage by order. Dispatch records link quantities to the buyer order and delivery reference. Invoicing rules and accounting exports must be confirmed with your accountant.</p>'),
            ("First release", "Choose a narrow first release", '<p>If missed dates are the main problem, start with order status, next action, due date and owner. If material reconciliation is the problem, prioritise job-work issues and receipts. Add costing, purchasing, invoicing or buyer access only after the first workflow is being used reliably.</p><ul class="feature-list"><li>Define who can view rates, approve changes and adjust stock.</li><li>Agree exports, backups and correction history.</li><li>Test migration with a small set of sample records.</li><li>Review the screens with the staff who enter the data.</li></ul>'),
            ("Discovery", "What to bring to a discovery conversation", '<p>A redacted order sheet, sample approval record, job-work register and one example of a delayed or disputed order are useful. Remove customer and employee details you do not need to share. We map the current process before recommending a custom build or an existing tool.</p><p>See our <a href="services-business-systems">CRM, ERP and billing services</a>, <a href="services-software">custom software approach</a> and <a href="services-ai-automation">automation services</a>.</p>'),
        ],
        "faqs": [("Do we need a complete ERP immediately?", "Usually the decision should start with the recurring operational problem. One connected order or job-work workflow may be a more useful first release than replacing every system at once."),
                 ("Can you work with our existing spreadsheets or accounting system?", "We review the available data, exports and integration permissions during discovery. Migration and accounting integration are separate deliverables with reconciliation checks."),
                 ("Will this automatically fix stock differences?", "No. The software can make movements and adjustments traceable, but accurate opening balances, consistent units and staff recording practices are still necessary.")],
    },
    "website-cost-erode": {
        "title": "What Does a Business Website Cost in Erode? | MUCO LABS",
        "description": "Understand what changes website cost in Erode: pages, content, enquiries, checkout and integrations. Compare build, hosting, support and SEO costs before quoting.",
        "h1": "What does a business website cost in Erode?", "label": "Website cost guide", "service": "Website design & development",
        "lead": "A useful website quote depends on what customers must be able to do, what content is ready and who will maintain it. MUCO LABS quotes from a written scope rather than publishing a price that leaves the essential work out. Start by choosing the type of website you actually need.",
        "sections": [
            ("Scope first", "Compare the scope before comparing the price", '<div class="table-scroll"><table><thead><tr><th scope="col">Website type</th><th scope="col">Main customer task</th><th scope="col">What changes the work</th></tr></thead><tbody><tr><th scope="row">Business information site</th><td>Understand services and contact you</td><td>Page count, copy, photography and editing needs</td></tr><tr><th scope="row">Enquiry or booking site</th><td>Request a quote or appointment</td><td>Form handling, availability, notifications and follow-up</td></tr><tr><th scope="row">Online store</th><td>Order and pay for products</td><td>Catalogue, stock, delivery, payments and refunds</td></tr><tr><th scope="row">Custom portal</th><td>Use an account to manage ongoing work</td><td>Roles, data, integrations, security and reporting</td></tr></tbody></table></div>'),
            ("Build vs running", "Separate build costs from running costs", '<p>Design, development, initial content entry and launch are one-time work unless the proposal states otherwise. Domain renewal, hosting, email and software subscriptions recur. Maintenance pays for agreed updates and support. Monthly SEO or content work is a separate service, and ad spend goes to the advertising platform. Ask for these as separate lines in every quote.</p>'),
            ("The proposal", "What a clear proposal should answer", '<ul class="feature-list"><li>Which pages, functions and content are included?</li><li>Who writes the copy and supplies approved images?</li><li>Where do enquiries arrive, and who follows them up?</li><li>Which accounts and code do you own after payment?</li><li>How are revisions, testing and acceptance handled?</li><li>Which third-party fees, taxes and support tasks are excluded?</li></ul><p>A low quote that omits content, enquiry handling or handover is difficult to compare with one that includes them.</p>'),
            ("Timeline", "How long will it take?", '<p>The schedule depends on the scope and when approved content, access and feedback are available. A small information site has fewer dependencies than a store or account-based portal. Ask for milestones covering content, design review, build, testing and launch, with responsibilities on both sides. We confirm dates in the proposal rather than promising a universal turnaround.</p>'),
            ("Redesign or rebuild", "Redesign or improve the existing website?", '<p>If customers understand the services and the content is editable, fixing speed, forms or confusing contact actions may be enough. A rebuild becomes more useful when the current structure cannot support the required workflow or is costly to maintain. A <a href="website-audit">free website review</a> can help decide the next step.</p><p>See the <a href="business-website-growth">business website and local search offer</a>, <a href="website-development-erode">website development in Erode</a> and our <a href="pricing">quoting process</a>.</p>'),
        ],
        "faqs": [("Can you give me a price before a full specification?", "We can start with a free conversation about the requirement. A useful written quote still needs agreed pages, functions, content responsibilities and exclusions."),
                 ("Does paying for a website guarantee Google rankings?", "No. A well-built website supports crawling, useful content and a clear customer journey. Search position also depends on relevance, competition and search-engine decisions."),
                 ("When should a business use custom software instead of Excel?", "Consider it when repeated data entry, conflicting versions, access permissions or missing follow-ups create a recurring operational cost. First map that cost and check whether an existing tool meets the need.")],
    },
}


def build_growth_page(slug):
    p = GROWTH_PAGES[slug]
    crumb = crumb_nav([("Home", "/"), (p["label"], None)])
    body = page_header(p["label"], p["h1"], p["lead"], extra=crumb + '<div class="btn-group mt-5"><a class="btn btn-accent" href="/contact?service=%s#start-project">Start a Project</a><a class="btn btn-whatsapp" href="%s" data-whatsapp>WhatsApp MUCO LABS</a></div>' % (quote(p["service"]), WHATSAPP_URL))
    for label, title, text in p["sections"]:
        body += ('<section class="section-divider"><div class="container container-narrow growth-copy">'
                 '<div class="section-head"><span class="eyebrow">%s</span><h2>%s</h2></div>%s</div></section>'
                 % (label, title, text))
    body += ('<section class="section-divider"><div class="container container-narrow">'
             '<div class="section-head"><span class="eyebrow">Before you ask</span>'
             '<h2>Questions before you start</h2></div>')
    for q, a in p["faqs"]:
        body += '<details class="faq-item"><summary><h3>%s</h3></summary><div class="faq-body"><p>%s</p></div></details>' % (q, a)
    body += '</div></section>' + final_cta("Describe the outcome you need", "We will help you define the next practical step and a written scope.")
    schemas = [ORG_JSONLD, breadcrumbs([("Home", ""), (p["label"], slug)]), faq_jsonld(p["faqs"])]
    if slug == "website-cost-erode":
        schemas.append(json.dumps({"@context": "https://schema.org", "@type": "WebPage", "url": DOMAIN + "/" + slug, "name": p["h1"]}))
    else:
        schemas.append(service_jsonld(p["label"], p["description"], slug))
    return render(slug + ".html", p["title"], p["description"], body, schema_blocks=schemas)
