import Link from "next/link";
import type { Metadata } from "next";
import { requireAccount } from "@muco/core/server";
import { formatDate, humanise } from "@muco/core";
import { EmptyState, Icon } from "@muco/ui";

export const metadata: Metadata = { title: "Certificates" };

function one<T>(value: unknown): T | null {
  return ((Array.isArray(value) ? value[0] : value) ?? null) as T | null;
}

// Every certificate the studio has ever issued, in one list.
//
// The serial is the point of this page. It is what an employer types into the
// verification address, it is what makes a forged certificate detectable, and
// it is generated by the database rather than by a page — MUCO-INT-<year>-<n>,
// counted per organisation per year inside the same transaction that writes
// the row, so two issued at once cannot collide.
export default async function CertificatesPage() {
  const { supabase, organizationId } = await requireAccount("admin");

  const { data: certificates } = await supabase
    .from("intern_certificates")
    .select("id,serial,issued_on,tools,mentor_name,approved_by_name,document_hash,intern_id,intern_profiles(user_id,track,starts_at,ends_at,profiles!intern_profiles_user_id_fkey(full_name))")
    .eq("organization_id", organizationId)
    .order("issued_on", { ascending: false });

  const rows = certificates ?? [];
  const thisYear = rows.filter(
    row => new Date(row.issued_on as string).getFullYear() === new Date().getFullYear(),
  ).length;

  return (
    <div className="page">
      <div className="page-head">
        <span className="eyebrow">Issued and verifiable</span>
        <h1>Certificates</h1>
        <p className="lede">
          Every certificate the studio has issued. Anybody holding a serial can check it at
          intern.mucolabs.com/verify without an account, and that page discloses the holder, the
          track, the dates and the status — nothing else.
        </p>
      </div>

      <section className="grid">
        <div className="metric">
          <span className="k">Issued in total</span>
          <span className="v">{rows.length}</span>
        </div>
        <div className="metric">
          <span className="k">Issued this year</span>
          <span className="v">{thisYear}</span>
        </div>
      </section>

      <section className="panel">
        <div className="panel-head">
          <h2>The register</h2>
          <Link className="btn sm quiet" href="/completions">
            <span>Waiting for approval</span>
            <Icon name="arrowRight" size={14} />
          </Link>
        </div>
        {rows.length === 0 ? (
          <EmptyState icon="award" title="None issued yet">
            A certificate is created when you approve a completed internship. It cannot be created
            any other way, and no certificate has ever existed without an administrator approving it.
          </EmptyState>
        ) : (
          <div className="tablewrap">
            <table>
              <caption className="sr-only">Certificates issued</caption>
              <thead>
                <tr>
                  <th scope="col">Serial</th>
                  <th scope="col">Holder</th>
                  <th scope="col">Track</th>
                  <th scope="col">Issued</th>
                  <th scope="col">Approved by</th>
                  <th scope="col">Mentor</th>
                </tr>
              </thead>
              <tbody>
                {rows.map(row => {
                  const intern = one<{
                    user_id: string; track: string;
                    profiles: unknown;
                  }>(row.intern_profiles);
                  const holder = one<{ full_name: string }>(intern?.profiles)?.full_name ?? "Unnamed";
                  return (
                    <tr key={row.id}>
                      <td className="mono">{row.serial}</td>
                      <td>
                        {intern?.user_id
                          ? <Link href={"/people/" + intern.user_id}>{holder}</Link>
                          : holder}
                      </td>
                      <td>{intern ? humanise(intern.track).replace("Intern ", "") : "—"}</td>
                      <td>{formatDate(row.issued_on)}</td>
                      <td>{row.approved_by_name}</td>
                      <td>{row.mentor_name ?? "Not recorded"}</td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        )}
      </section>

      <p className="notice">
        <Icon name="shield" size={14} />
        <span>
          The approver is stored by name as well as by identifier. Deleting an old administrator one
          day sets the identifier to null; the document still says who approved it.
        </span>
      </p>
    </div>
  );
}
