"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";

// Checklist 6.9: the founder approving a certificate, on a screen.
//
// The rule was never missing -- approved_by is NOT NULL, so no certificate has
// ever existed without a founder behind it. What was missing was any way to be
// that founder except by writing SQL, which meant the most ceremonial act in
// the product happened in a database console.
//
// The serial is not typed here. It is generated by issue_certificate, because
// a number somebody types is a number somebody eventually repeats, and this
// one goes on a document an employer will check.

export function IssueCertificate({
  internId, name, mentorName, mentorNote, recommendedAt,
}: {
  internId: string; name: string;
  mentorName: string | null; mentorNote: string | null; recommendedAt: string | null;
}) {
  const router = useRouter();
  const [open, setOpen] = useState(false);
  const [tools, setTools] = useState("");
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function issue() {
    setError(null);
    const client = createClient();
    if (!client) { setError("This workspace is not configured for sign-in."); return; }

    setBusy(true);
    const { error: failed } = await client.rpc("issue_certificate", {
      p_intern_id: internId,
      p_tools: tools.split(",").map(entry => entry.trim()).filter(Boolean),
      p_mentor_name: mentorName,
    });
    setBusy(false);

    if (failed) { setError(failed.message); return; }
    setOpen(false);
    router.refresh();
  }

  if (!open) {
    return (
      <div className="issuecell">
        {recommendedAt ? (
          <p className="muted">
            {mentorName ? mentorName + " recommended this" : "Recommended"} on{" "}
            {new Date(recommendedAt).toLocaleDateString("en-IN", { day: "numeric", month: "short" })}
            {mentorNote ? " — " + mentorNote : ""}
          </p>
        ) : (
          <p className="muted">No mentor recommendation yet.</p>
        )}
        <button type="button" className="primary compact" onClick={() => setOpen(true)}>
          Approve and issue
        </button>
      </div>
    );
  }

  return (
    <div className="accessconfirm">
      <label htmlFor={"tools-" + internId}>What did {name} work with?</label>
      <input id={"tools-" + internId} value={tools} disabled={busy}
        placeholder="React, TypeScript, Supabase"
        onChange={event => setTools(event.target.value)} />
      <div className="accessbuttons">
        <button type="button" className="primary compact" disabled={busy} onClick={issue}>
          {busy ? "Issuing…" : "Issue certificate"}
        </button>
        <button type="button" className="secondary compact" disabled={busy}
          onClick={() => { setOpen(false); setError(null); }}>
          Cancel
        </button>
      </div>
      {error && <p className="error" role="alert">{error}</p>}
      <p className="muted">
        Separate the tools with commas. They are printed on the certificate, and the intern
        cannot change them afterwards. The serial is generated, not typed.
      </p>
    </div>
  );
}
